# Port du middle-service
server.port=8081

# URL du service SOAP
soap.service.url=http://localhost:8083/ws

# Configuration du nom de l'application
spring.application.name=middle-service

# Configuration des logs
logging.level.com.example.middle_service=DEBUG
logging.level.org.springframework.ws=DEBUG

# Configuration Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
